### ISSUE TITLE
Feats are incomplete. 

### ISSUE THREAD

**Issue by JoshPoole09** [Git-Lamurette/Notion-DnD#2]
Grappler is the only feat that is in the data.

**Comment by Git-Lamurette** [comment]
Hi JoshPoole09

Unfortunately this is the only feat that is listed inside the DnD 5e SRD, you can reference it here on page 75. I also thought I was missing data as well when I first looked into this project.

https://www.dndbeyond.com/resources/1781-systems-reference-document-srd?srsltid=AfmBOooblayh4mfxjJBalcVzi4bsvOgfRVk6Cl1WtZRTCSYp_HIkdpu_
