### ISSUE TITLE
Backgrounds are incomplete

### ISSUE THREAD

**Issue by JoshPoole09** [Git-Lamurette/Notion-DnD#3]
Acolyte is the only background.

**Comment by Git-Lamurette** [comment]
Hi JoshPoole09

Unfortunately this is the only background that is listed inside the DnD 5e SRD, you can reference it here on page 60.

https://www.dndbeyond.com/resources/1781-systems-reference-document-srd?srsltid=AfmBOooblayh4mfxjJBalcVzi4bsvOgfRVk6Cl1WtZRTCSYp_HIkdpu_
